[package]
name = "aster-gpu"
version = "0.1.0"
edition.workspace = true

[dependencies]
component.workspace = true
log.workspace = true
ostd.workspace = true
spin.workspace = true

[lints]
workspace = true